version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestProject
  gitServerName: jfl
  gitUrl: https://github.com/levjason
  gitUsername: levjason
  gitBranch: main
services:
- serviceName: project.test.integrations:fs2
  packages:
  - name: TestProject
    version: "1.0"
